"""Factor Library API — serves factor metrics, correlations, crowding analysis."""
from fastapi import APIRouter

router = APIRouter()

FACTORS = [
    {"id":"gpa","name":"Gross Profitability (GPA)","category":"Quality","source":"Novy-Marx 2013",
     "sharpe":1.02,"alpha":0.067,"r2":0.65,"mdd":-0.356,"oos_sharpe":0.80,"decay":0.27,
     "crowding":"low","trend":"stable","status":"effective",
     "description":"Gross profit / total assets. Purest quality alpha (R²=0.65), low factor exposure."},
    {"id":"ff5alpha","name":"FF5 Rolling Alpha","category":"Factor Model","source":"Rolling regression",
     "sharpe":1.05,"alpha":0.073,"r2":0.69,"mdd":-0.513,"oos_sharpe":0.71,"decay":0.40,
     "crowding":"medium","trend":"declining","status":"effective",
     "description":"36-month rolling alpha from Fama-French 5-factor regression. High alpha but has HML+UMD exposure."},
    {"id":"roe","name":"Return on Equity","category":"Quality","source":"Hou, Xue, Zhang 2015",
     "sharpe":0.93,"alpha":0.042,"r2":0.66,"mdd":-0.348,"oos_sharpe":0.58,"decay":0.46,
     "crowding":"low","trend":"rising","status":"effective",
     "description":"Net income / common equity. Clean alpha, recovering in recent years."},
    {"id":"mom12","name":"12-1 Momentum","category":"Momentum","source":"Jegadeesh & Titman 1993",
     "sharpe":0.81,"alpha":0.025,"r2":0.65,"mdd":-0.413,"oos_sharpe":0.91,"decay":-0.13,
     "crowding":"high","trend":"declining","status":"crowded",
     "description":"12-month return skipping recent month. Heavy UMD loading (β=0.61), declining 3yr Sharpe."},
    {"id":"ag","name":"Asset Growth","category":"Investment","source":"Cooper, Gulen, Schill 2008",
     "sharpe":0.86,"alpha":0.036,"r2":0.75,"mdd":-0.376,"oos_sharpe":1.03,"decay":-0.26,
     "crowding":"medium","trend":"declining","status":"marginal",
     "description":"Low asset growth = higher returns. High R² suggests factor crowding."},
    {"id":"ep","name":"Earnings-to-Price","category":"Value","source":"Basu 1977",
     "sharpe":0.76,"alpha":0.040,"r2":0.74,"mdd":-0.399,"oos_sharpe":0.72,"decay":0.08,
     "crowding":"high","trend":"rising","status":"crowded",
     "description":"Net income / market cap. Crowded via HML exposure (β=0.46). Recent value comeback."},
    {"id":"bm","name":"Book-to-Market","category":"Value","source":"Fama & French 1992",
     "sharpe":0.74,"alpha":0.050,"r2":0.87,"mdd":-0.558,"oos_sharpe":1.33,"decay":-1.20,
     "crowding":"high","trend":"rising","status":"crowded",
     "description":"Book equity / market equity. Extremely crowded — R²=0.87 means it IS the HML factor."},
    {"id":"accel","name":"Momentum Acceleration","category":"Momentum","source":"Gettleman & Marks 2006",
     "sharpe":0.49,"alpha":0.008,"r2":0.54,"mdd":-0.473,"oos_sharpe":0.60,"decay":-0.24,
     "crowding":"low","trend":"stable","status":"marginal",
     "description":"Difference between recent and older 3M momentum. Low alpha, weak standalone performance."},
    {"id":"ivol","name":"Idiosyncratic Volatility","category":"Volatility","source":"Ang et al. 2006",
     "sharpe":0.58,"alpha":-0.013,"r2":0.65,"mdd":-0.389,"oos_sharpe":0.47,"decay":0.26,
     "crowding":"medium","trend":"stable","status":"ineffective",
     "description":"Low IVOL anomaly. Negative alpha in our sample — factor appears ineffective with costs."},
    {"id":"high52","name":"52-Week High","category":"Momentum","source":"George & Hwang 2004",
     "sharpe":0.57,"alpha":-0.010,"r2":0.60,"mdd":-0.472,"oos_sharpe":0.69,"decay":-0.26,
     "crowding":"medium","trend":"stable","status":"ineffective",
     "description":"Proximity to 12-month high. Near-zero alpha, mostly UMD exposure."},
    {"id":"quality_mom","name":"Quality × Momentum","category":"Interaction","source":"Interaction signal",
     "sharpe":0.84,"alpha":0.026,"r2":0.57,"mdd":-0.321,"oos_sharpe":0.96,"decay":-0.17,
     "crowding":"low","trend":"stable","status":"effective",
     "description":"GPA rank × Momentum rank. Only buys stocks with BOTH high quality AND strong momentum."},
    {"id":"value_quality","name":"Value × Quality","category":"Interaction","source":"Interaction signal",
     "sharpe":0.80,"alpha":0.038,"r2":0.62,"mdd":-0.242,"oos_sharpe":0.99,"decay":-0.24,
     "crowding":"low","trend":"stable","status":"effective",
     "description":"BM rank × ROE rank. Avoids value traps by requiring profitability confirmation."},
    {"id":"orth_gpa","name":"Orthogonal GPA","category":"Orthogonal","source":"Residual after size+value",
     "sharpe":1.06,"alpha":0.070,"r2":0.54,"mdd":-0.261,"oos_sharpe":1.16,"decay":-0.12,
     "crowding":"low","trend":"stable","status":"effective",
     "description":"GPA after stripping size and value exposures. R² drops from 0.65→0.54, purer alpha."},
    {"id":"orth_roe","name":"Orthogonal ROE","category":"Orthogonal","source":"Residual after size+value",
     "sharpe":0.92,"alpha":0.054,"r2":0.57,"mdd":-0.260,"oos_sharpe":1.02,"decay":-0.13,
     "crowding":"low","trend":"stable","status":"effective",
     "description":"ROE after stripping size and value. Captures pure profitability alpha."},
    # ── Vol Factors ──
    {"id":"lowvol","name":"Low Volatility","category":"Volatility","source":"Ang et al. 2006",
     "sharpe":0.45,"alpha":-0.002,"r2":0.35,"mdd":-0.360,"oos_sharpe":0.01,"decay":0.98,
     "crowding":"medium","trend":"declining","status":"ineffective",
     "description":"12-month realized vol, long low-vol. Severe OOS decay. Works better as combo ingredient."},
    {"id":"vov","name":"Vol-of-Vol","category":"Volatility","source":"Baltussen et al. 2018",
     "sharpe":0.72,"alpha":0.014,"r2":0.45,"mdd":-0.271,"oos_sharpe":0.28,"decay":0.70,
     "crowding":"low","trend":"stable","status":"marginal",
     "description":"Volatility of volatility. Low R²=0.45 (independent). Lowest MDD among vol factors."},
    {"id":"downvol","name":"Downside Volatility","category":"Volatility","source":"Ang, Chen, Xing 2006",
     "sharpe":0.68,"alpha":0.011,"r2":0.53,"mdd":-0.423,"oos_sharpe":0.51,"decay":0.23,
     "crowding":"low","trend":"stable","status":"marginal",
     "description":"Semi-deviation (only negative returns). Most robust OOS among vol factors."},
    {"id":"maxret","name":"MAX Return","category":"Volatility","source":"Bali, Cakici, Whitelaw 2011",
     "sharpe":0.49,"alpha":0.004,"r2":0.43,"mdd":-0.363,"oos_sharpe":0.02,"decay":0.97,
     "crowding":"low","trend":"declining","status":"ineffective",
     "description":"Max single-month return in past 12mo. Lottery effect. Near-zero OOS alpha."},
    {"id":"skew","name":"Skewness","category":"Volatility","source":"Boyer, Mitton, Vorkink 2010",
     "sharpe":0.78,"alpha":0.028,"r2":0.72,"mdd":-0.396,"oos_sharpe":0.80,"decay":-0.01,
     "crowding":"medium","trend":"stable","status":"effective",
     "description":"Rolling 12M skewness. Best standalone vol factor. Zero OOS decay. But R²=0.72 (some crowding)."},
    {"id":"volts","name":"Vol Term Structure","category":"Volatility","source":"Adrian & Rosenberg 2008",
     "sharpe":0.75,"alpha":0.019,"r2":0.73,"mdd":-0.446,"oos_sharpe":0.87,"decay":-0.13,
     "crowding":"medium","trend":"rising","status":"effective",
     "description":"3M vol / 12M vol ratio. OOS actually better than IS. High R² though."},
    {"id":"volmom","name":"Vol Momentum","category":"Volatility","source":"Empirical",
     "sharpe":0.68,"alpha":0.003,"r2":0.69,"mdd":-0.404,"oos_sharpe":0.83,"decay":-0.26,
     "crowding":"medium","trend":"rising","status":"marginal",
     "description":"3-month change in realized vol. Stocks with decreasing vol outperform. Strong OOS."},
    # ── New Fundamental Factors ──
    {"id":"price_to_sales","name":"Price-to-Sales","category":"Value","source":"Compustat sale/mktcap",
     "sharpe":1.075,"alpha":0.069,"r2":0.78,"mdd":-0.375,"oos_sharpe":1.22,"decay":-0.19,
     "crowding":"medium","trend":"rising","status":"effective",
     "description":"Low price-to-sales ratio. Sharpe 1.08, best OOS among new factors (1.22)."},
    {"id":"leverage_change","name":"Leverage Change","category":"Quality","source":"Compustat dltt/at delta",
     "sharpe":0.982,"alpha":0.055,"r2":0.71,"mdd":-0.363,"oos_sharpe":0.74,"decay":0.29,
     "crowding":"low","trend":"stable","status":"effective",
     "description":"Decreasing leverage = positive signal. Sharpe 0.98, moderate OOS decay."},
    {"id":"revenue_momentum","name":"Revenue Momentum","category":"Quality","source":"Compustat sale YoY",
     "sharpe":0.919,"alpha":0.039,"r2":0.74,"mdd":-0.431,"oos_sharpe":1.04,"decay":-0.18,
     "crowding":"low","trend":"rising","status":"effective",
     "description":"Year-over-year revenue growth. Full Sharpe 0.92, OOS 1.04 (improving)."},
    {"id":"momentum_breadth","name":"Momentum Breadth","category":"Momentum","source":"% positive months in 12M",
     "sharpe":0.889,"alpha":0.031,"r2":0.66,"mdd":-0.400,"oos_sharpe":1.24,"decay":-0.56,
     "crowding":"low","trend":"rising","status":"effective",
     "description":"Fraction of past 12 months positive. Full Sharpe 0.89, OOS 1.24 (strongest OOS improvement)."},
    {"id":"earnings_quality","name":"Earnings Quality","category":"Quality","source":"NI growth - AT growth",
     "sharpe":0.841,"alpha":0.029,"r2":0.76,"mdd":-0.449,"oos_sharpe":0.77,"decay":0.10,
     "crowding":"medium","trend":"stable","status":"marginal",
     "description":"Earnings growth minus asset growth. Detects accounting-driven vs real earnings."},
    {"id":"momentum_quality_int","name":"Momentum × Quality","category":"Interaction","source":"mom12 * gpa",
     "sharpe":0.921,"alpha":0.042,"r2":0.68,"mdd":-0.382,"oos_sharpe":0.86,"decay":0.07,
     "crowding":"low","trend":"stable","status":"effective",
     "description":"Interaction: only buy high-momentum stocks that are also high-quality."},
    {"id":"defensive_value_int","name":"Defensive Value","category":"Interaction","source":"lowvol * ep",
     "sharpe":0.782,"alpha":0.035,"r2":0.55,"mdd":-0.310,"oos_sharpe":1.21,"decay":-0.89,
     "crowding":"low","trend":"rising","status":"effective",
     "description":"Low-vol value stocks. R2=0.55 (independent), OOS 1.21, lowest crowding."},
    # ── A-Share Factor Proxies ──
    {"id":"cn_lowvol","name":"CN Low Volatility","category":"CN A-Share","source":"CSI LowVol Index",
     "sharpe":0.93,"alpha":0.057,"r2":None,"mdd":-0.054,"oos_sharpe":0.00,"decay":1.0,
     "crowding":"low","trend":"strong","status":"effective",
     "description":"CSI Low-Vol Index excess over CSI 300. Strongest A-share factor (Sh=0.93). Only 53 months of data."},
    {"id":"cn_dividend","name":"CN Dividend Premium","category":"CN A-Share","source":"CSI Dividend Index",
     "sharpe":0.41,"alpha":0.023,"r2":None,"mdd":-0.109,"oos_sharpe":0.00,"decay":1.0,
     "crowding":"low","trend":"stable","status":"marginal",
     "description":"CSI Dividend Index excess over CSI 300. Moderate but stable."},
    {"id":"cn_smb","name":"CN Size (Small-Big)","category":"CN A-Share","source":"CSI500-CSI300",
     "sharpe":0.18,"alpha":0.016,"r2":None,"mdd":-0.434,"oos_sharpe":0.56,"decay":-2.11,
     "crowding":"high","trend":"rising","status":"marginal",
     "description":"CSI500 minus CSI300. Small-cap premium weak full-sample but recovering in OOS."},
    {"id":"cn_hml","name":"CN Value (HML)","category":"CN A-Share","source":"CSI Value-Growth",
     "sharpe":-0.01,"alpha":-0.012,"r2":None,"mdd":-0.517,"oos_sharpe":0.33,"decay":2.43,
     "crowding":"high","trend":"cycling","status":"ineffective",
     "description":"CSI Value minus Growth. Near-zero full-sample Sharpe. Extreme 3-year cycles (±47%)."},
    {"id":"cn_growth","name":"CN Growth Excess","category":"CN A-Share","source":"GEM-CSI300",
     "sharpe":0.30,"alpha":0.043,"r2":None,"mdd":-0.488,"oos_sharpe":0.42,"decay":-0.56,
     "crowding":"medium","trend":"volatile","status":"marginal",
     "description":"创业板指 excess over CSI 300. High vol, moderate return. OOS improving."},
    # ── HK Factors ──
    {"id":"hk_mom12m","name":"HK 12M Momentum","category":"HK","source":"yfinance HSI",
     "sharpe":0.70,"alpha":0.118,"r2":None,"mdd":-0.315,"oos_sharpe":0.11,"decay":0.90,
     "crowding":"medium","trend":"declining","status":"marginal",
     "description":"HSI 12-month multi-TF momentum. Highest IS Sharpe but 90% OOS decay."},
    {"id":"hk_mom6m","name":"HK 6M Momentum","category":"HK","source":"yfinance HSI",
     "sharpe":0.56,"alpha":0.116,"r2":None,"mdd":-0.261,"oos_sharpe":0.26,"decay":0.65,
     "crowding":"low","trend":"stable","status":"effective",
     "description":"6-month momentum on HSI stocks. A-rated. Best single HK factor by Sharpe+MDD balance."},
    {"id":"hk_downvol","name":"HK Downside Vol","category":"HK","source":"yfinance HSI",
     "sharpe":0.51,"alpha":0.081,"r2":None,"mdd":-0.298,"oos_sharpe":0.31,"decay":0.49,
     "crowding":"low","trend":"stable","status":"effective",
     "description":"Downside semi-deviation on HSI. Only 6/6 gate-passing HK factor."},
    {"id":"hk_skew","name":"HK Skewness","category":"HK","source":"yfinance HSI",
     "sharpe":0.54,"alpha":0.093,"r2":None,"mdd":-0.364,"oos_sharpe":0.16,"decay":0.81,
     "crowding":"medium","trend":"declining","status":"marginal",
     "description":"Rolling 12M skewness on HSI. High IS but severe OOS decay."},
    {"id":"hk_lowvol","name":"HK Low Vol","category":"HK","source":"yfinance HSI",
     "sharpe":0.45,"alpha":0.070,"r2":None,"mdd":-0.314,"oos_sharpe":0.39,"decay":0.18,
     "crowding":"low","trend":"stable","status":"marginal",
     "description":"Low realized vol on HSI. Most stable OOS (only 18% decay)."},
]

CORRELATION = {
    "labels": ["gpa","ff5a","roe","mom12","ag","ep","bm","accel","ivol"],
    "values": [
        [1.00,0.68,0.75,0.56,0.74,0.68,0.59,0.60,0.61],
        [0.68,1.00,0.61,0.71,0.57,0.59,0.45,0.64,0.41],
        [0.75,0.61,1.00,0.55,0.70,0.71,0.58,0.61,0.80],
        [0.56,0.71,0.55,1.00,0.52,0.47,0.40,0.47,0.50],
        [0.74,0.57,0.70,0.52,1.00,0.73,0.77,0.64,0.64],
        [0.68,0.59,0.71,0.47,0.73,1.00,0.84,0.63,0.72],
        [0.59,0.45,0.58,0.40,0.77,0.84,1.00,0.61,0.68],
        [0.60,0.64,0.61,0.47,0.64,0.63,0.61,1.00,0.56],
        [0.61,0.41,0.80,0.50,0.64,0.72,0.68,0.56,1.00],
    ]
}


@router.get("/library")
async def get_factor_library():
    return {"factors": FACTORS, "correlation": CORRELATION}
